### ISSUE TITLE
Android Ndk 17b issue

### ISSUE THREAD

**Issue by thegameguy** [MichaelStott/KivMob#39] opened 2019-03-03 12:41 UTC
I am getting error while building with ndk 17b
Full log: https://pastebin.com/R0LiwV86
Thanks!

**Comment by thegameguy** [comment] 2019-03-03 13:06
I am going to get ndk 17c. I hope its going to work with kivmob arrangment.

**Comment by MichaelStott** [comment] 2019-03-03 23:24
Not sure what the issue is. Could you post the buildozer.spec file?

**Comment by thegameguy** [comment] 2019-03-04 13:04
Unfortunately, kivent recipes have been deleted from latest P4a. That is a cheif issue for me in this case.

**Comment by MichaelStott** [comment] 2019-03-07 02:26
Ah, sorry to hear that. This seems to be something the KivEnt maintainers will have to fix. Closing for now.

**Closed by MichaelStott** 2019-03-07 02:26 UTC

**Comment by thegameguy** [comment] 2019-03-14 23:37
Hi, confirming the ndk 17c works with kivmob. Just catching up !!!!!!!!!
