### ISSUE TITLE
Ads not showing (support)

### ISSUE THREAD

**Issue by Artotim** [MichaelStott/KivMob#54] opened 2019-10-02 16:29 UTC
Hello Michael,
I'm trying to display some ads on my app, so i started running your example code.
The thing is, I've managed to sohw the Test ads using the test IDs, the problem is when I try to use my IDs generated by AdMob. It shows nothing.
Here's what I'm trying to do:

    from kivmob import KivMob

    from kivy.app import App
    from kivy.uix.button import Button

    class InterstitialTest(App):
    """ Display an interstitial ad on button release.
    """

    def build(self):
        self.ads = KivMob('ca-app-pub-XXXXXXXXXXXXXXXXX)
        self.ads.new_interstitial('ca-app-pub-XXXXXXXXXXXXXXXXX')
        self.ads.request_interstitial()
        return Button(text='Show Interstitial',
                      on_release=lambda a:self.ads.show_interstitial())

    def on_resume(self):
        self.ads.request_interstitial()

    if __name__ == "__main__":
        InterstitialTest().run()

I already double checked the buildozer.spec to match what you've said in your tutorial. Is there anything wrong with my code? Or the problem is with AdMob itself?

**Comment by MichaelStott** [comment] 2019-10-02 22:41
Updated to remove your AdMob ad IDs. I believe the problem is with AdMob here. It can take some time (as long as 24 hours) before AdMob begins serving live ads to your application. I would wait and try again later.

**Comment by MichaelStott** [comment] 2019-10-03 22:25
Closing for now. Let me know if the issue persists.

**Closed by MichaelStott** 2019-10-03 22:25 UTC
Labels: question

**Comment by Artotim** [comment] 2019-10-04 12:14
It's been more than 48h now and still nothing. But I've seen many users with the same problem with AdMob, so I'll try to contact them for a solution.
Thanks for answering this and many thanks for you creating this lib.

**Comment by Develp10** [comment] 2020-01-11 13:31
@Artotim  hi , did you find the solution ?

**Comment by Artotim** [comment] 2020-01-11 14:45
@Develp10 Yes, apparently they only start giving you some ads after there is some requests. So if you're showing the test ads then everything is fine. Just release your app and when it reach a certain amout of users the ads will start to pop.
Also you can see if is there any resquests, even tho no ads are showing, in your google ad account.

**Comment by Spidey611** [comment] 2022-05-13 18:10
@Artotim In my case even test ads are not working........ Please can you help me....... I am using the Interstitials code example shown in the official documentation of kivmob...... here - [http://kivmob.com/tutorials.html](url).............. Please can you help me!!!
