### ISSUE TITLE
app crashes on startup using banners

### ISSUE THREAD

**Issue by thegameguy** [MichaelStott/KivMob#13] opened 2018-09-15 17:12 UTC
Hi, My app crashes on startup with the traceback below. 

I/python  (14077):  Traceback (most recent call last):
I/python  (14077):    File "/home/vapo/test5/.buildozer/android/platform/build/dists/glowing/private/lib/python2.7/site-packages/android/runnable.py", line 35, in run
I/python  (14077):    File "/home/vapo/test5/.buildozer/android/platform/build/dists/glowing/private/lib/python2.7/site-packages/kivmob.py", line 98, in new_banner
I/python  (14077):    File "/home/vapo/test5/.buildozer/android/platform/bject has no attribute 'iteritems'
build/dists/glowing/private/lib/python2.7/site-packages/kivmob.py", line 148, in _build_msg
I/python  (14077):  AttributeError: 'str' object has no attribute 'iteritems'

and this code i added as it is in android manifest file

<activity android:name="com.google.ads.AdActivity"
	  
android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"/>

<com.google.ads.AdView android:id="@+id/adView"
		     android:layout_width="wrap_content"
		     android:layout_height="wrap_content"
		     ads:adUnitId="MY_AD_UNIT_ID"
		     ads:adSize="BANNER"
		     ads:testDevices="TEST_EMULATOR, TEST_DEVICE_ID"
		     ads:loadAdOnCreate="true"/>

**Comment by thegameguy** [comment] 2018-09-15 23:30
but the python error persists, AttributeError: 'str' object has no attribute 'iteritems'

**Comment by thegameguy** [comment] 2018-09-16 23:59
ads = KivMob("APP_ID")
ads.add_test_device("TEST_DEVICE_ID")
ads.new_banner("ca-app-pub-3940256099942544/6300978111") #sample banner ad unit
ads.request_banner()
def show_banner(self. *args):
    ads.show_banner()

**Comment by thegameguy** [comment] 2018-09-17 00:01
Since Google is not supporting android api below 26. is there any provision in python-for-android-admob for this current issue.

**Comment by MichaelStott** [comment] 2018-09-21 22:13
Closing this, as it is a duplicate of the more recent issue you opened.

**Closed** 2018-09-21 23:37 UTC
Labels: duplicate
